#ifndef APPDEFINES_H
#define APPDEFINES_H

#define IVR_ACCOUNT_NAME "mvnivr"
#define APP_USERAGENT "MVN IVR"

#define SEVER_PORT_DEFAULT 5060

#define MEDIA_SERVER_HOST_DEFAULT "127.0.0.1"
#define MEDIA_SERVER_PORT_DEFAULT 10000

#endif // APPDEFINES_H
